platform :ios, '11.0'

target 'LottiePlayground' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottiePlayground
  pod 'lottie-ios'
  pod 'SwiftLint'

  target 'LottiePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
